# Generated by Django 4.2.2 on 2023-06-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('openai_api_key', models.CharField(max_length=200, null=True)),
                ('proritingaid_api_key', models.CharField(max_length=200, null=True)),
                ('salt', models.CharField(max_length=200)),
                ('admin', models.BooleanField(default=False)),
                ('special_user', models.BooleanField(default=False)),
                ('subscribed', models.BooleanField(default=False)),
                ('subscription_id', models.CharField(max_length=200, null=True)),
                ('usage', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Essays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_essay', models.CharField(max_length=64000)),
                ('rephrased_essay', models.CharField(max_length=64000, null=True)),
                ('timefield', models.DateTimeField(auto_now_add=True, null=True)),
                ('byuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
