# Generated by Django 4.2.2 on 2023-07-03 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('proritingaid_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('salt', models.CharField(blank=True, max_length=200, null=True)),
                ('subscribed', models.BooleanField(default=False)),
                ('subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('usage', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
