# Generated by Django 4.2.2 on 2023-07-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextrafields',
            old_name='proritingaid_api_key',
            new_name='prowritingaid_api_key',
        ),
    ]
