# Generated by Django 4.2.2 on 2023-11-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_proritingaid_api_key_userextrafields_prowritingaid_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextrafields',
            name='hide_api_key',
            field=models.BooleanField(default=False),
        ),
    ]
