# Generated by Django 4.2.2 on 2023-11-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_subscription_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='customer_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
