# Generated by Django 4.2.2 on 2024-04-09 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_plans_words_length_subscription_usage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('context', models.BooleanField(default=False)),
                ('randomness', models.IntegerField(default=1)),
                ('tone', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('adj', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
