# Generated by Django 4.2.2 on 2024-05-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_settingsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='essays',
            name='model',
            field=models.CharField(default='gpt-3.5-turbo', max_length=128000),
        ),
    ]
